algoritmo "L05B"

// Disciplina   : [Lógica de Programação]
// Professor    : Jailson Costas do Santos
// Descrição    : Apresenta a tabuada de multiplicar (1 a 10) de um número qualquer
// Autor(a)     : Gabriel Franco Ferreira
// Data atual   : 13/09/2026

var
// Seção de Declarações das variáveis
   numero, contador: inteiro

inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite um número: ")
   leia(numero)

   para contador de 1 ate 10 faca
      escreval(numero, " x ", contador, " = ", numero * contador)
   fimpara

fimalgoritmo