algoritmo "L05F"

// Disciplina   : [Lógica de Programação]
// Professor    : Jailson Costas do Santos
// Descrição    : Apresenta os números divisíveis por 4 que sejam menores que 200
// Autor(a)     : Gabriel Franco Ferreira
// Data atual   : 26/09/2026

var
// Seção de Declarações das variáveis
   contador: inteiro

inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   para contador de 1 ate 199 faca
      se (contador mod 4 = 0) entao
         escreval(contador)
      fimse
   fimpara

fimalgoritmo